apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-service
    port: 8080 # porta do service | porta do computador -> porta do service -> porta do container
    targetPort: 8080 # porta do container
    protocol: TCP

